{"level":"error","message":"uncaught exceptionuncaught exception","stack":"Error: uncaught exception\n    at Object.<anonymous> (I:\\node-program\\vidly\\index.js:34:7)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)\n    at internal/main/run_main_module.js:17:11"}
{"level":"error","message":"uncaught exceptionuncaught exception","stack":"Error: uncaught exception\n    at Object.<anonymous> (I:\\node-program\\vidly\\index.js:33:7)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)\n    at internal/main/run_main_module.js:17:11"}
{"level":"error","message":"uncaught exceptionuncaught exception","stack":"Error: uncaught exception\n    at Object.<anonymous> (I:\\node-program\\vidly\\index.js:33:7)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)\n    at internal/main/run_main_module.js:17:11"}
{"message":"uncaught exception","level":"error"}
